extract_task:
  description: >
    Use the 'Video Screenshot and Transcript Extractor' tool on the URL {youtube_url}. 
    The tool will automatically determine the optimal screenshot interval based on the video length. 
    Ensure the output clearly lists the file paths of all saved screenshots and the transcript file.
  expected_output: >
    A clean summary listing the file paths and timestamps for all extracted screenshots and the transcript path.
  agent: video_engineer

analysis_task:
  description: >
    SPEED-OPTIMIZED ANALYSIS: Rapidly analyze all screenshots from the Video Content Engineer. 
    Work efficiently through each screenshot file: 
    1. Quickly identify key visual elements, text, and educational content using VisionTool. 
    2. Extract main concepts and themes without excessive detail. 
    3. Note important text, titles, or data visible in images. 
    4. Focus on educational value and learning objectives. 
    5. Work through screenshots systematically and efficiently. 
    Prioritize speed while maintaining quality. Provide concise but comprehensive analysis.
  expected_output: >
    Efficient visual analysis for each screenshot with timestamps, focusing on key concepts and educational content.
  agent: content_analyzer
  context:
    - extract_task

synthesis_task:
  description: >
    SPEED-OPTIMIZED SYNTHESIS: Rapidly create a comprehensive study guide using analysis and transcript data. 
    Work efficiently to: 
    1. Quickly read transcript file (if available) using FileReadTool. 
    2. Efficiently match visual analysis with transcript content by timestamp. 
    3. Create structured, informative notes combining visual and audio information. 
    4. Extract key concepts and main points without excessive elaboration. 
    5. Use clear headings, bullet points, and organized structure. 
    6. Include relevant transcript quotes when they add educational value. 
    7. Focus on learning objectives and practical study value. 
    8. Maintain quality while prioritizing speed and efficiency. 
    Generate a professional study guide optimized for both speed and educational value.
  expected_output: >
    A well-structured study guide in Markdown format efficiently combining visual and audio information with key concepts and learning materials.
  agent: note_synthesizer
  context:
    - extract_task
    - analysis_task
  output_file: final_study_guide.md